### ISSUE TITLE
`Timeline-view` only works with `tns run android`?

### ISSUE THREAD

**Issue by mid787** [PanayotCankov/timeline-view#4]
Currently if I do this : 

`tns run android | timeline-view` - then I do see the logs in the console ,also when I press `ctrl+c` - it does create the `times.html` file - so we're  all set..

*But* -  after  installing  webpack , I need to run this : `npm run start-android-bundle`

Which is : (in `package.json`) :

  `"start-android-bundle": "npm run ns-bundle --android --run-app" `

_BTW - if I run `npm run start-android-bundle` everything is ok but the file (`time.html`) is **not** created._

So I've tried to do this : 

 

    npm run ns-bundle --android --run-app | timeline-view 
 

But then it doesn't work : 

    child process exited with code 127
    
    npm ERR! Windows_NT 10.0.15063
    npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ns-bundle" "--android" "--run-app"
    npm ERR! node v7.9.0
    npm ERR! npm  v4.2.0
    npm ERR! file C:\WINDOWS\system32\cmd.exe
    npm ERR! code ELIFECYCLE
    npm ERR! errno ENOENT
    npm ERR! syscall spawn
    npm ERR! Groceries@1.0.0 ns-bundle: `ns-bundle`
    npm ERR! spawn ENOENT

**Question :** 

What is the right way to create the `times.html` file with webpack ?

(I want to measure uptime for the app via looking at the graph.)

**Comment by buuhuu** [comment]
First build the bundle
`npm run build-android-bundle`
Then start it 
`tns run android --bundle --disable-npm-install | timeline-view`

**Comment by phacic** [comment]
`Times.html` not created in `tns 4.2` using the answer above
